services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/app/
    links:
      - php
    networks:
      - pg-network

  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    env_file: .env
    ports:
      - "5433:5432"
    networks:
      - pg-network

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    env_file: .env
    volumes:
      - .:/app
    networks:
      - pg-network
    command: >
      sh -c "
        until pg_isready -h $${DB_HOST} -p $${DB_PORT}; do
          echo '⏳  Waiting for Postgres...' ; sleep 1 ;
        done ;
        php setup.php && php-fpm
      "

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin4
    env_file: .env
    ports:
      - "5050:80"
    networks:
      - pg-network
    volumes:
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json

networks:
  pg-network:

volumes:
  pg-data:
